### ISSUE TITLE
JS Error: illegal character

### ISSUE THREAD

**Issue by franglais125** [tliron/em-dash#1]
Hi!

First time trying to get to run the extension. I opened this issue to get more info, but also in case someone else hits the same problem.

The use of "`" quotes prevents the extension from loading.I suspect that this is because I am running Gnome 3.22, so with GJS based on SpiderMonkey24.

Is the use of "`" allowed with newer GJS versions perhaps?

Cheers!
Fran

**Comment by tliron** [comment]
Thanks, Fran! Actually, just today I updated the metadata to specify GNOME 3.24 only. :) Your analysis is correct.

**Comment by franglais125** [comment]
Sounds good! Good hacking!
