### ISSUE TITLE
feature request - dock transparency 

### ISSUE THREAD

**Issue by kwalker99** [tliron/em-dash#3]
could you guys add transparency options like dash to dock? dash to dock is really well featured when it comes to customisation of appearance, but lacks the icon/window grabbing features of em-dash

**Comment by tliron** [comment]
I'm not so sure it's a good idea. The styling of the dock has to do with the GNOME Shell theme: some have the dock transparent, others don't. I think overriding the theme style might be the job of a different extension, otherwise it will be a slippery slope of adding many, many different overrides.

**Comment by kwalker99** [comment]
the panel and the dock transparency should be independent of the theme

**Comment by tliron** [comment]
I understand that this is your feature request. But it is absolutely not how GNOME normally works.

I think I would be more comfortable having a separate extension, maybe called "Theme tweaks", that allows you to change transparency and other features across many shell elements. It would thus work on all extensions, like this one, instead of being specific here.

**Comment by kwalker99** [comment]
ok, I guess the idea with em-dash is to take it's appearance from the shell
theme. Are you able to answer my other issue I have open about the quit
menu not appearing?

**Comment by tliron** [comment]
Correct. There are some visual changes you can make in Em-Dash, but they relate specifically to the new position of the dock, not to its styling.

I will look at the other issue very soon! Thank you for helping test!

**Comment by kwalker99** [comment]
helping test..lol

I'm using it on a production laptop :-) it is very stable, better than dash
to dock i have found, the ability to grab orphan windows/icons is genius.

**Comment by tliron** [comment]
That's very kind of you to say. :) I made it as easy as possible to hack, hope you delve into the code and make it cooler!
