### ISSUE TITLE
Settings -> crashed

### ISSUE THREAD

**Issue by mykaul** [tliron/em-dash#4]
I've installed it, clicked on 'Settings' and got:
Error: Expected type utf8 for Argument 'text' but got type 'integer'

Stack trace:
  _escape@/home/ykaul/.local/share/gnome-shell/extensions/em-dash@github.com_tliron/prefs.js:691:9
  _init@/home/ykaul/.local/share/gnome-shell/extensions/em-dash@github.com_tliron/prefs.js:104:14
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
  buildPrefsWidget@/home/ykaul/.local/share/gnome-shell/extensions/em-dash@github.com_tliron/prefs.js:37:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  

I'm running it on Fedora 28, gnome-shell-3.28.2-1.fc28.x86_64

**Comment by grompes** [comment]
Подтверждаю.

Вот только сейчас скачал с gnome extensions и ЗДОРОВЕННЫЕ (большого размера) иконки неизменить =((

Ubuntu 18.04.2

**Comment by tliron** [comment]
Thank you everyone for the bug report! The issue seems to be with the zip uploaded to GNOME Extensions web site, it works well from GitHub. I am trying to debug it today and will re-release on GNOME Extensions.

**Comment by tliron** [comment]
Fixed and uploaded to GNOME Extensions. It takes some time to be reviewed there, but hopefully it will be soon!

**Comment by tliron** [comment]
Finally it has been reviewed by GNOME Extensions site. I would appreciate if you verify that it works!

**Comment by nyex** [comment]
Working perfectly for me. Thank you very much.
