### ISSUE TITLE
Not working with Ubuntu 18.10

### ISSUE THREAD

**Issue by kwalker99** [tliron/em-dash#6]
Hi

Finally jumped to Ubuntu 18.10, but em-dash is not working.

Is there any ETA to create a fix?

**Comment by tliron** [comment]
Could you help me debug? What exactly isn't working? Could you provide some logs?

**Comment by kwalker99** [comment]
I have a fresh vanilla install of 18.10, I install from the Gnome
extensions website and it says error.

Yes, which logs do you need?

**Comment by tliron** [comment]
I'm sorry, I still don't understand the situation exactly. Are you saying that it doesn't install at all? Do other extensions from the GNOME extensions web site install OK?

Could you try installing it from here in GitHub?

**Comment by kwalker99** [comment]
Hi Tal

Yes that’s correct, it wasn’t working after upgrading from 18.04 to 18.10 and it doesn’t install with a fresh vanilla install of 18.10.

Yes other extensions install fine. 

Kind regards

Kevin Walker

On 11 Nov 2018, at 00:43, Tal Liron <notifications@github.com> wrote:

I'm sorry, I still don't understand the situation exactly. Are you saying that it doesn't install at all? Do other extensions from the GNOME extensions web site install OK?

Could you try installing it from here in GitHub?

**Comment by tliron** [comment]
Thanks for the clarification. Have you tried installing it directly from GitHub yet?

**Comment by kwalker99** [comment]
not yet, had to rebuild my system and needed a working system, so installed 18.04. I do however have a 18.10 partition for testing, so will clone the repo and give it a try.

**Comment by kwalker99** [comment]
ok, v5.0 installs perfectly on 18.10
